[myservers]
server1-i4d-tp06 ansible_host=localhost ansible_user=root ansible_ssh_pass=P@ssw0rd1 ansible_port=22

# Example with IP address:
# server1-i4d-tp06 ansible_host=192.168.1.100 ansible_user=root ansible_ssh_pass=P@ssw0rd1 ansible_port=22